### PR TITLE
Updates to title and intro/summary

### PR DESCRIPTION
**Pull request by yeekangc**
Edits to improve the title and intro/summary

### CODE REVIEW

**Comment by yeekangc** [comment]
Not sure if you noticed my PR, @mahsankhaan.  Hope this helps.

**Comment by yeekangc** [comment]
Thank you, @mahsankhaan.

**Comment by mahsankhaan** [comment]
@yeekangc do you think there is anything else to add ?

**Comment by yeekangc** [comment]
I don't have additional comments at the moment.  Thank you.

**Pull request merged**
